//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace touchvg.core {

public enum GiHandleTypes {
  kGiHandleVertex,
  kGiHandleHotVertex,
  kGiHandleRotate,
  kGiHandleLock,
  kGiHandleUnlock,
  kGiHandleCancel,
  kGiHandleAccept,
  kGiHandleNode,
  kGiHandleCenter,
  kGiHandleMidPoint,
  kGiHandleQuadrant,
  kGiHandleTangent,
  kGiHandleIntersect,
  kGiHandleParallel,
  kGiHandleNear,
  kGiHandlePivot,
  kGiHandleOverturn,
  kGiHandleCustom = 20
}

}
