//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace touchvg.core {

public class MgActionDispatcher : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MgActionDispatcher(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MgActionDispatcher obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~MgActionDispatcher() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          touchvgPINVOKE.delete_MgActionDispatcher(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual bool showInSelect(MgMotion sender, int selState, MgShape shape, Box2d selbox) {
    bool ret = touchvgPINVOKE.MgActionDispatcher_showInSelect(swigCPtr, MgMotion.getCPtr(sender), selState, MgShape.getCPtr(shape), Box2d.getCPtr(selbox));
    if (touchvgPINVOKE.SWIGPendingException.Pending) throw touchvgPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool showInDrawing(MgMotion sender, MgShape shape) {
    bool ret = touchvgPINVOKE.MgActionDispatcher_showInDrawing(swigCPtr, MgMotion.getCPtr(sender), MgShape.getCPtr(shape));
    return ret;
  }

  public virtual bool doAction(MgMotion sender, int action) {
    bool ret = touchvgPINVOKE.MgActionDispatcher_doAction(swigCPtr, MgMotion.getCPtr(sender), action);
    return ret;
  }

}

}
