/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace touchvg.core {

using System;
using System.Runtime.InteropServices;

public class MgActionDispatcher : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MgActionDispatcher(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(MgActionDispatcher obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~MgActionDispatcher() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          touchvgPINVOKE.delete_MgActionDispatcher(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public virtual bool showInSelect(MgMotion sender, int selState, MgShape shape, Box2d selbox) {
    bool ret = touchvgPINVOKE.MgActionDispatcher_showInSelect(swigCPtr, MgMotion.getCPtr(sender), selState, MgShape.getCPtr(shape), Box2d.getCPtr(selbox));
    if (touchvgPINVOKE.SWIGPendingException.Pending) throw touchvgPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool showInDrawing(MgMotion sender, MgShape shape) {
    bool ret = touchvgPINVOKE.MgActionDispatcher_showInDrawing(swigCPtr, MgMotion.getCPtr(sender), MgShape.getCPtr(shape));
    return ret;
  }

  public virtual bool doAction(MgMotion sender, int action) {
    bool ret = touchvgPINVOKE.MgActionDispatcher_doAction(swigCPtr, MgMotion.getCPtr(sender), action);
    return ret;
  }

}

}
