/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace touchvg.core {

using System;
using System.Runtime.InteropServices;

public class MgBaseRect : MgBaseShape {
  private HandleRef swigCPtr;

  internal MgBaseRect(IntPtr cPtr, bool cMemoryOwn) : base(touchvgPINVOKE.MgBaseRect_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(MgBaseRect obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~MgBaseRect() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          touchvgPINVOKE.delete_MgBaseRect(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public new static int Type() {
    int ret = touchvgPINVOKE.MgBaseRect_Type();
    return ret;
  }

  public Point2d getCenter() {
    Point2d ret = new Point2d(touchvgPINVOKE.MgBaseRect_getCenter(swigCPtr), true);
    return ret;
  }

  public Box2d getRect() {
    Box2d ret = new Box2d(touchvgPINVOKE.MgBaseRect_getRect(swigCPtr), true);
    return ret;
  }

  public float getWidth() {
    float ret = touchvgPINVOKE.MgBaseRect_getWidth(swigCPtr);
    return ret;
  }

  public float getHeight() {
    float ret = touchvgPINVOKE.MgBaseRect_getHeight(swigCPtr);
    return ret;
  }

  public float getAngle() {
    float ret = touchvgPINVOKE.MgBaseRect_getAngle(swigCPtr);
    return ret;
  }

  public bool isEmpty(float minDist) {
    bool ret = touchvgPINVOKE.MgBaseRect_isEmpty(swigCPtr, minDist);
    return ret;
  }

  public bool isOrtho() {
    bool ret = touchvgPINVOKE.MgBaseRect_isOrtho(swigCPtr);
    return ret;
  }

  public void setRect2P(Point2d pt1, Point2d pt2) {
    touchvgPINVOKE.MgBaseRect_setRect2P(swigCPtr, Point2d.getCPtr(pt1), Point2d.getCPtr(pt2));
    if (touchvgPINVOKE.SWIGPendingException.Pending) throw touchvgPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setRectWithAngle(Point2d pt1, Point2d pt2, float angle, Point2d basept) {
    touchvgPINVOKE.MgBaseRect_setRectWithAngle(swigCPtr, Point2d.getCPtr(pt1), Point2d.getCPtr(pt2), angle, Point2d.getCPtr(basept));
    if (touchvgPINVOKE.SWIGPendingException.Pending) throw touchvgPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setRect4P(Point2d points) {
    touchvgPINVOKE.MgBaseRect_setRect4P(swigCPtr, Point2d.getCPtr(points));
  }

  public void setCenter(Point2d pt) {
    touchvgPINVOKE.MgBaseRect_setCenter(swigCPtr, Point2d.getCPtr(pt));
    if (touchvgPINVOKE.SWIGPendingException.Pending) throw touchvgPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setSquare(bool square) {
    touchvgPINVOKE.MgBaseRect_setSquare(swigCPtr, square);
  }

  public override bool isCurve() {
    bool ret = (SwigDerivedClassHasMethod("isCurve", swigMethodTypes16) ? touchvgPINVOKE.MgBaseRect_isCurveSwigExplicitMgBaseRect(swigCPtr) : touchvgPINVOKE.MgBaseRect_isCurve(swigCPtr));
    return ret;
  }

  protected MgBaseRect() : this(touchvgPINVOKE.new_MgBaseRect(), true) {
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("clone", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateMgBaseRect_0(SwigDirectorclone);
    if (SwigDerivedClassHasMethod("copy", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateMgBaseRect_1(SwigDirectorcopy);
    if (SwigDerivedClassHasMethod("release", swigMethodTypes2))
      swigDelegate2 = new SwigDelegateMgBaseRect_2(SwigDirectorrelease);
    if (SwigDerivedClassHasMethod("equals", swigMethodTypes3))
      swigDelegate3 = new SwigDelegateMgBaseRect_3(SwigDirectorequals);
    if (SwigDerivedClassHasMethod("getType", swigMethodTypes4))
      swigDelegate4 = new SwigDelegateMgBaseRect_4(SwigDirectorgetType);
    if (SwigDerivedClassHasMethod("isKindOf", swigMethodTypes5))
      swigDelegate5 = new SwigDelegateMgBaseRect_5(SwigDirectorisKindOf);
    if (SwigDerivedClassHasMethod("setOwner", swigMethodTypes6))
      swigDelegate6 = new SwigDelegateMgBaseRect_6(SwigDirectorsetOwner);
    if (SwigDerivedClassHasMethod("getExtent", swigMethodTypes7))
      swigDelegate7 = new SwigDelegateMgBaseRect_7(SwigDirectorgetExtent);
    if (SwigDerivedClassHasMethod("update", swigMethodTypes8))
      swigDelegate8 = new SwigDelegateMgBaseRect_8(SwigDirectorupdate);
    if (SwigDerivedClassHasMethod("transform", swigMethodTypes9))
      swigDelegate9 = new SwigDelegateMgBaseRect_9(SwigDirectortransform);
    if (SwigDerivedClassHasMethod("clear", swigMethodTypes10))
      swigDelegate10 = new SwigDelegateMgBaseRect_10(SwigDirectorclear);
    if (SwigDerivedClassHasMethod("clearCachedData", swigMethodTypes11))
      swigDelegate11 = new SwigDelegateMgBaseRect_11(SwigDirectorclearCachedData);
    if (SwigDerivedClassHasMethod("getPointCount", swigMethodTypes12))
      swigDelegate12 = new SwigDelegateMgBaseRect_12(SwigDirectorgetPointCount);
    if (SwigDerivedClassHasMethod("getPoint", swigMethodTypes13))
      swigDelegate13 = new SwigDelegateMgBaseRect_13(SwigDirectorgetPoint);
    if (SwigDerivedClassHasMethod("setPoint", swigMethodTypes14))
      swigDelegate14 = new SwigDelegateMgBaseRect_14(SwigDirectorsetPoint);
    if (SwigDerivedClassHasMethod("isClosed", swigMethodTypes15))
      swigDelegate15 = new SwigDelegateMgBaseRect_15(SwigDirectorisClosed);
    if (SwigDerivedClassHasMethod("isCurve", swigMethodTypes16))
      swigDelegate16 = new SwigDelegateMgBaseRect_16(SwigDirectorisCurve);
    if (SwigDerivedClassHasMethod("hitTest", swigMethodTypes17))
      swigDelegate17 = new SwigDelegateMgBaseRect_17(SwigDirectorhitTest);
    if (SwigDerivedClassHasMethod("hitTestBox", swigMethodTypes18))
      swigDelegate18 = new SwigDelegateMgBaseRect_18(SwigDirectorhitTestBox);
    if (SwigDerivedClassHasMethod("draw", swigMethodTypes19))
      swigDelegate19 = new SwigDelegateMgBaseRect_19(SwigDirectordraw);
    if (SwigDerivedClassHasMethod("save", swigMethodTypes20))
      swigDelegate20 = new SwigDelegateMgBaseRect_20(SwigDirectorsave);
    if (SwigDerivedClassHasMethod("load", swigMethodTypes21))
      swigDelegate21 = new SwigDelegateMgBaseRect_21(SwigDirectorload);
    if (SwigDerivedClassHasMethod("getHandleCount", swigMethodTypes22))
      swigDelegate22 = new SwigDelegateMgBaseRect_22(SwigDirectorgetHandleCount);
    if (SwigDerivedClassHasMethod("getHandlePoint", swigMethodTypes23))
      swigDelegate23 = new SwigDelegateMgBaseRect_23(SwigDirectorgetHandlePoint);
    if (SwigDerivedClassHasMethod("setHandlePoint", swigMethodTypes24))
      swigDelegate24 = new SwigDelegateMgBaseRect_24(SwigDirectorsetHandlePoint);
    if (SwigDerivedClassHasMethod("isHandleFixed", swigMethodTypes25))
      swigDelegate25 = new SwigDelegateMgBaseRect_25(SwigDirectorisHandleFixed);
    if (SwigDerivedClassHasMethod("getHandleType", swigMethodTypes26))
      swigDelegate26 = new SwigDelegateMgBaseRect_26(SwigDirectorgetHandleType);
    if (SwigDerivedClassHasMethod("offset", swigMethodTypes27))
      swigDelegate27 = new SwigDelegateMgBaseRect_27(SwigDirectoroffset);
    if (SwigDerivedClassHasMethod("setFlag", swigMethodTypes28))
      swigDelegate28 = new SwigDelegateMgBaseRect_28(SwigDirectorsetFlag);
    if (SwigDerivedClassHasMethod("getTypeName", swigMethodTypes29))
      swigDelegate29 = new SwigDelegateMgBaseRect_29(SwigDirectorgetTypeName);
    touchvgPINVOKE.MgBaseRect_director_connect(swigCPtr, swigDelegate0, swigDelegate1, swigDelegate2, swigDelegate3, swigDelegate4, swigDelegate5, swigDelegate6, swigDelegate7, swigDelegate8, swigDelegate9, swigDelegate10, swigDelegate11, swigDelegate12, swigDelegate13, swigDelegate14, swigDelegate15, swigDelegate16, swigDelegate17, swigDelegate18, swigDelegate19, swigDelegate20, swigDelegate21, swigDelegate22, swigDelegate23, swigDelegate24, swigDelegate25, swigDelegate26, swigDelegate27, swigDelegate28, swigDelegate29);
  }

  private bool SwigDerivedClassHasMethod(string methodName, Type[] methodTypes) {
    System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(MgBaseRect));
    return hasDerivedMethod;
  }

  private IntPtr SwigDirectorclone() {
    return MgObject.getCPtr(clone()).Handle;
  }

  private void SwigDirectorcopy(IntPtr src) {
    copy(new MgObject(src, false));
  }

  private void SwigDirectorrelease() {
    release();
  }

  private bool SwigDirectorequals(IntPtr src) {
    return equals(new MgObject(src, false));
  }

  private int SwigDirectorgetType() {
    return getType();
  }

  private bool SwigDirectorisKindOf(int type) {
    return isKindOf(type);
  }

  private void SwigDirectorsetOwner(IntPtr owner) {
    setOwner((owner == IntPtr.Zero) ? null : new MgShape(owner, false));
  }

  private IntPtr SwigDirectorgetExtent() {
    return Box2d.getCPtr(getExtent()).Handle;
  }

  private void SwigDirectorupdate() {
    update();
  }

  private void SwigDirectortransform(IntPtr mat) {
    transform(new Matrix2d(mat, false));
  }

  private void SwigDirectorclear() {
    clear();
  }

  private void SwigDirectorclearCachedData() {
    clearCachedData();
  }

  private int SwigDirectorgetPointCount() {
    return getPointCount();
  }

  private IntPtr SwigDirectorgetPoint(int index) {
    return Point2d.getCPtr(getPoint(index)).Handle;
  }

  private void SwigDirectorsetPoint(int index, IntPtr pt) {
    setPoint(index, new Point2d(pt, false));
  }

  private bool SwigDirectorisClosed() {
    return isClosed();
  }

  private bool SwigDirectorisCurve() {
    return isCurve();
  }

  private float SwigDirectorhitTest(IntPtr pt, float tol, IntPtr res) {
    return hitTest(new Point2d(pt, false), tol, new MgHitResult(res, false));
  }

  private bool SwigDirectorhitTestBox(IntPtr rect) {
    return hitTestBox(new Box2d(rect, false));
  }

  private bool SwigDirectordraw(int mode, IntPtr gs, IntPtr ctx, int segment) {
    return draw(mode, new GiGraphics(gs, false), new GiContext(ctx, false), segment);
  }

  private bool SwigDirectorsave(IntPtr s) {
    return save((s == IntPtr.Zero) ? null : new MgStorage(s, false));
  }

  private bool SwigDirectorload(IntPtr factory, IntPtr s) {
    return load((factory == IntPtr.Zero) ? null : new MgShapeFactory(factory, false), (s == IntPtr.Zero) ? null : new MgStorage(s, false));
  }

  private int SwigDirectorgetHandleCount() {
    return getHandleCount();
  }

  private IntPtr SwigDirectorgetHandlePoint(int index) {
    return Point2d.getCPtr(getHandlePoint(index)).Handle;
  }

  private bool SwigDirectorsetHandlePoint(int index, IntPtr pt, float tol) {
    return setHandlePoint(index, new Point2d(pt, false), tol);
  }

  private bool SwigDirectorisHandleFixed(int index) {
    return isHandleFixed(index);
  }

  private int SwigDirectorgetHandleType(int index) {
    return getHandleType(index);
  }

  private bool SwigDirectoroffset(IntPtr vec, int segment) {
    return offset(new Vector2d(vec, false), segment);
  }

  private void SwigDirectorsetFlag(int bit, bool on) {
    setFlag((MgShapeBit)bit, on);
  }

  private string SwigDirectorgetTypeName() {
    return getTypeName();
  }

  public delegate IntPtr SwigDelegateMgBaseRect_0();
  public delegate void SwigDelegateMgBaseRect_1(IntPtr src);
  public delegate void SwigDelegateMgBaseRect_2();
  public delegate bool SwigDelegateMgBaseRect_3(IntPtr src);
  public delegate int SwigDelegateMgBaseRect_4();
  public delegate bool SwigDelegateMgBaseRect_5(int type);
  public delegate void SwigDelegateMgBaseRect_6(IntPtr owner);
  public delegate IntPtr SwigDelegateMgBaseRect_7();
  public delegate void SwigDelegateMgBaseRect_8();
  public delegate void SwigDelegateMgBaseRect_9(IntPtr mat);
  public delegate void SwigDelegateMgBaseRect_10();
  public delegate void SwigDelegateMgBaseRect_11();
  public delegate int SwigDelegateMgBaseRect_12();
  public delegate IntPtr SwigDelegateMgBaseRect_13(int index);
  public delegate void SwigDelegateMgBaseRect_14(int index, IntPtr pt);
  public delegate bool SwigDelegateMgBaseRect_15();
  public delegate bool SwigDelegateMgBaseRect_16();
  public delegate float SwigDelegateMgBaseRect_17(IntPtr pt, float tol, IntPtr res);
  public delegate bool SwigDelegateMgBaseRect_18(IntPtr rect);
  public delegate bool SwigDelegateMgBaseRect_19(int mode, IntPtr gs, IntPtr ctx, int segment);
  public delegate bool SwigDelegateMgBaseRect_20(IntPtr s);
  public delegate bool SwigDelegateMgBaseRect_21(IntPtr factory, IntPtr s);
  public delegate int SwigDelegateMgBaseRect_22();
  public delegate IntPtr SwigDelegateMgBaseRect_23(int index);
  public delegate bool SwigDelegateMgBaseRect_24(int index, IntPtr pt, float tol);
  public delegate bool SwigDelegateMgBaseRect_25(int index);
  public delegate int SwigDelegateMgBaseRect_26(int index);
  public delegate bool SwigDelegateMgBaseRect_27(IntPtr vec, int segment);
  public delegate void SwigDelegateMgBaseRect_28(int bit, bool on);
  public delegate string SwigDelegateMgBaseRect_29();

  private SwigDelegateMgBaseRect_0 swigDelegate0;
  private SwigDelegateMgBaseRect_1 swigDelegate1;
  private SwigDelegateMgBaseRect_2 swigDelegate2;
  private SwigDelegateMgBaseRect_3 swigDelegate3;
  private SwigDelegateMgBaseRect_4 swigDelegate4;
  private SwigDelegateMgBaseRect_5 swigDelegate5;
  private SwigDelegateMgBaseRect_6 swigDelegate6;
  private SwigDelegateMgBaseRect_7 swigDelegate7;
  private SwigDelegateMgBaseRect_8 swigDelegate8;
  private SwigDelegateMgBaseRect_9 swigDelegate9;
  private SwigDelegateMgBaseRect_10 swigDelegate10;
  private SwigDelegateMgBaseRect_11 swigDelegate11;
  private SwigDelegateMgBaseRect_12 swigDelegate12;
  private SwigDelegateMgBaseRect_13 swigDelegate13;
  private SwigDelegateMgBaseRect_14 swigDelegate14;
  private SwigDelegateMgBaseRect_15 swigDelegate15;
  private SwigDelegateMgBaseRect_16 swigDelegate16;
  private SwigDelegateMgBaseRect_17 swigDelegate17;
  private SwigDelegateMgBaseRect_18 swigDelegate18;
  private SwigDelegateMgBaseRect_19 swigDelegate19;
  private SwigDelegateMgBaseRect_20 swigDelegate20;
  private SwigDelegateMgBaseRect_21 swigDelegate21;
  private SwigDelegateMgBaseRect_22 swigDelegate22;
  private SwigDelegateMgBaseRect_23 swigDelegate23;
  private SwigDelegateMgBaseRect_24 swigDelegate24;
  private SwigDelegateMgBaseRect_25 swigDelegate25;
  private SwigDelegateMgBaseRect_26 swigDelegate26;
  private SwigDelegateMgBaseRect_27 swigDelegate27;
  private SwigDelegateMgBaseRect_28 swigDelegate28;
  private SwigDelegateMgBaseRect_29 swigDelegate29;

  private static Type[] swigMethodTypes0 = new Type[] {  };
  private static Type[] swigMethodTypes1 = new Type[] { typeof(MgObject) };
  private static Type[] swigMethodTypes2 = new Type[] {  };
  private static Type[] swigMethodTypes3 = new Type[] { typeof(MgObject) };
  private static Type[] swigMethodTypes4 = new Type[] {  };
  private static Type[] swigMethodTypes5 = new Type[] { typeof(int) };
  private static Type[] swigMethodTypes6 = new Type[] { typeof(MgShape) };
  private static Type[] swigMethodTypes7 = new Type[] {  };
  private static Type[] swigMethodTypes8 = new Type[] {  };
  private static Type[] swigMethodTypes9 = new Type[] { typeof(Matrix2d) };
  private static Type[] swigMethodTypes10 = new Type[] {  };
  private static Type[] swigMethodTypes11 = new Type[] {  };
  private static Type[] swigMethodTypes12 = new Type[] {  };
  private static Type[] swigMethodTypes13 = new Type[] { typeof(int) };
  private static Type[] swigMethodTypes14 = new Type[] { typeof(int), typeof(Point2d) };
  private static Type[] swigMethodTypes15 = new Type[] {  };
  private static Type[] swigMethodTypes16 = new Type[] {  };
  private static Type[] swigMethodTypes17 = new Type[] { typeof(Point2d), typeof(float), typeof(MgHitResult) };
  private static Type[] swigMethodTypes18 = new Type[] { typeof(Box2d) };
  private static Type[] swigMethodTypes19 = new Type[] { typeof(int), typeof(GiGraphics), typeof(GiContext), typeof(int) };
  private static Type[] swigMethodTypes20 = new Type[] { typeof(MgStorage) };
  private static Type[] swigMethodTypes21 = new Type[] { typeof(MgShapeFactory), typeof(MgStorage) };
  private static Type[] swigMethodTypes22 = new Type[] {  };
  private static Type[] swigMethodTypes23 = new Type[] { typeof(int) };
  private static Type[] swigMethodTypes24 = new Type[] { typeof(int), typeof(Point2d), typeof(float) };
  private static Type[] swigMethodTypes25 = new Type[] { typeof(int) };
  private static Type[] swigMethodTypes26 = new Type[] { typeof(int) };
  private static Type[] swigMethodTypes27 = new Type[] { typeof(Vector2d), typeof(int) };
  private static Type[] swigMethodTypes28 = new Type[] { typeof(MgShapeBit), typeof(bool) };
  private static Type[] swigMethodTypes29 = new Type[] {  };
}

}
