//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace touchvg.core {

public enum MgContextAction {
  kMgActionInvalid = 0,
  kMgActionSelAll = 1,
  kMgActionSelReset = 2,
  kMgActionDraw = 3,
  kMgActionCancel = 4,
  kMgActionDelete = 5,
  kMgActionClone = 6,
  kMgActionFixedLength = 7,
  kMgActionFreeLength = 8,
  kMgActionLocked = 9,
  kMgActionUnlocked = 10,
  kMgActionEditVertex = 11,
  kMgActionHideVertex = 12,
  kMgActionClosed = 13,
  kMgActionOpened = 14,
  kMgActionAddVertex = 15,
  kMgActionDelVertex = 16,
  kMgActionGroup = 17,
  kMgActionUngroup = 18,
  kMgActionOverturn = 19,
  kMgActionCustomized = 100
}

}
