//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace touchvg.core {

public enum MgSelDrawFlags {
  kMgSelDrawDragLine = 1 << 1,
  kMgSelDrawDragDot = 1 << 2,
  kMgSelDrawGroupBorder = 1 << 3,
  kMgSelDrawActionBorder = 1 << 4,
  kMgSelDrawSelBorder = 1 << 5,
  kMgSelDrawBlueShape = 1 << 6,
  kMgSelDrawHandle = 1 << 7,
  kMgSelDrawXformBox = 1 << 16,
  kMgSelDrawNearPt = 1 << 17
}

}
