/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace touchvg.core {

using System;
using System.Runtime.InteropServices;

public class MgStringCallback : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MgStringCallback(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(MgStringCallback obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~MgStringCallback() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          touchvgPINVOKE.delete_MgStringCallback(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public virtual void onGetString(string text) {
    touchvgPINVOKE.MgStringCallback_onGetString(swigCPtr, text);
  }

  public MgStringCallback() : this(touchvgPINVOKE.new_MgStringCallback(), true) {
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("onGetString", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateMgStringCallback_0(SwigDirectoronGetString);
    touchvgPINVOKE.MgStringCallback_director_connect(swigCPtr, swigDelegate0);
  }

  private bool SwigDerivedClassHasMethod(string methodName, Type[] methodTypes) {
    System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(MgStringCallback));
    return hasDerivedMethod;
  }

  private void SwigDirectoronGetString(string text) {
    onGetString(text);
  }

  public delegate void SwigDelegateMgStringCallback_0(string text);

  private SwigDelegateMgStringCallback_0 swigDelegate0;

  private static Type[] swigMethodTypes0 = new Type[] { typeof(string) };
}

}
