//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace touchvg.core {

public class touchvg {
  public static float _MGZERO {
    get {
      float ret = touchvgPINVOKE._MGZERO_get();
      return ret;
    } 
  }

  public static float _M_E {
    get {
      float ret = touchvgPINVOKE._M_E_get();
      return ret;
    } 
  }

  public static float _M_LOG2E {
    get {
      float ret = touchvgPINVOKE._M_LOG2E_get();
      return ret;
    } 
  }

  public static float _M_LOG10E {
    get {
      float ret = touchvgPINVOKE._M_LOG10E_get();
      return ret;
    } 
  }

  public static float _M_LN2 {
    get {
      float ret = touchvgPINVOKE._M_LN2_get();
      return ret;
    } 
  }

  public static float _M_LN10 {
    get {
      float ret = touchvgPINVOKE._M_LN10_get();
      return ret;
    } 
  }

  public static float _M_PI {
    get {
      float ret = touchvgPINVOKE._M_PI_get();
      return ret;
    } 
  }

  public static float _M_PI_2 {
    get {
      float ret = touchvgPINVOKE._M_PI_2_get();
      return ret;
    } 
  }

  public static float _M_PI_4 {
    get {
      float ret = touchvgPINVOKE._M_PI_4_get();
      return ret;
    } 
  }

  public static float _M_1_PI {
    get {
      float ret = touchvgPINVOKE._M_1_PI_get();
      return ret;
    } 
  }

  public static float _M_2_PI {
    get {
      float ret = touchvgPINVOKE._M_2_PI_get();
      return ret;
    } 
  }

  public static float _M_2_SQRTPI {
    get {
      float ret = touchvgPINVOKE._M_2_SQRTPI_get();
      return ret;
    } 
  }

  public static float _M_SQRT2 {
    get {
      float ret = touchvgPINVOKE._M_SQRT2_get();
      return ret;
    } 
  }

  public static float _M_SQRT1_2 {
    get {
      float ret = touchvgPINVOKE._M_SQRT1_2_get();
      return ret;
    } 
  }

  public static float _M_2PI {
    get {
      float ret = touchvgPINVOKE._M_2PI_get();
      return ret;
    } 
  }

  public static float _M_PI_3 {
    get {
      float ret = touchvgPINVOKE._M_PI_3_get();
      return ret;
    } 
  }

  public static float _M_PI_6 {
    get {
      float ret = touchvgPINVOKE._M_PI_6_get();
      return ret;
    } 
  }

  public static float _M_D2R {
    get {
      float ret = touchvgPINVOKE._M_D2R_get();
      return ret;
    } 
  }

  public static float _M_R2D {
    get {
      float ret = touchvgPINVOKE._M_R2D_get();
      return ret;
    } 
  }

  public static float _M_1_SQRPI {
    get {
      float ret = touchvgPINVOKE._M_1_SQRPI_get();
      return ret;
    } 
  }

  public static float _FLT_MIN {
    get {
      float ret = touchvgPINVOKE._FLT_MIN_get();
      return ret;
    } 
  }

  public static float _FLT_MAX {
    get {
      float ret = touchvgPINVOKE._FLT_MAX_get();
      return ret;
    } 
  }

}

}
