/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package democmds.core;

public class democmdsJNI {
  public final static native void delete_Floats(long jarg1);
  public final static native long new_Floats__SWIG_0(int jarg1);
  public final static native long new_Floats__SWIG_1();
  public final static native void Floats_setSize(long jarg1, Floats jarg1_, int jarg2);
  public final static native long new_Floats__SWIG_2(float jarg1, float jarg2);
  public final static native long new_Floats__SWIG_3(float jarg1, float jarg2, float jarg3, float jarg4);
  public final static native int Floats_count(long jarg1, Floats jarg1_);
  public final static native float Floats_get(long jarg1, Floats jarg1_, int jarg2);
  public final static native void Floats_set__SWIG_0(long jarg1, Floats jarg1_, int jarg2, float jarg3);
  public final static native void Floats_set__SWIG_1(long jarg1, Floats jarg1_, int jarg2, float jarg3, float jarg4);
  public final static native void delete_Chars(long jarg1);
  public final static native long new_Chars__SWIG_0(int jarg1);
  public final static native long new_Chars__SWIG_1();
  public final static native void Chars_setSize(long jarg1, Chars jarg1_, int jarg2);
  public final static native long new_Chars__SWIG_2(char jarg1, char jarg2);
  public final static native long new_Chars__SWIG_3(char jarg1, char jarg2, char jarg3, char jarg4);
  public final static native int Chars_count(long jarg1, Chars jarg1_);
  public final static native char Chars_get(long jarg1, Chars jarg1_, int jarg2);
  public final static native void Chars_set__SWIG_0(long jarg1, Chars jarg1_, int jarg2, char jarg3);
  public final static native void Chars_set__SWIG_1(long jarg1, Chars jarg1_, int jarg2, char jarg3, char jarg4);
  public final static native int DemoCmdsGate_registerCmds(int jarg1);
  public final static native int DemoCmdsGate_getDimensions(int jarg1, long jarg2, Floats jarg2_, long jarg3, Chars jarg3_);
  public final static native long new_DemoCmdsGate();
  public final static native void delete_DemoCmdsGate(long jarg1);
}
