/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package democmds.core;

public class DemoCmdsGate {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DemoCmdsGate(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DemoCmdsGate obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        democmdsJNI.delete_DemoCmdsGate(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static int registerCmds(int mgView) {
    return democmdsJNI.DemoCmdsGate_registerCmds(mgView);
  }

  public static int getDimensions(int mgView, Floats vars, Chars types) {
    return democmdsJNI.DemoCmdsGate_getDimensions(mgView, Floats.getCPtr(vars), vars, Chars.getCPtr(types), types);
  }

  public DemoCmdsGate() {
    this(democmdsJNI.new_DemoCmdsGate(), true);
  }

}
