/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package rhcad.touchvg.core;

public final class GiGestureState {
  public final static GiGestureState kGiGesturePossible = new GiGestureState("kGiGesturePossible");
  public final static GiGestureState kGiGestureBegan = new GiGestureState("kGiGestureBegan");
  public final static GiGestureState kGiGestureMoved = new GiGestureState("kGiGestureMoved");
  public final static GiGestureState kGiGestureEnded = new GiGestureState("kGiGestureEnded");
  public final static GiGestureState kGiGestureCancel = new GiGestureState("kGiGestureCancel");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GiGestureState swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GiGestureState.class + " with value " + swigValue);
  }

  private GiGestureState(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GiGestureState(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GiGestureState(String swigName, GiGestureState swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GiGestureState[] swigValues = { kGiGesturePossible, kGiGestureBegan, kGiGestureMoved, kGiGestureEnded, kGiGestureCancel };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

