/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package rhcad.touchvg.core;

public class Longs {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Longs(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Longs obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        touchvgJNI.delete_Longs(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Longs(int n) {
    this(touchvgJNI.new_Longs__SWIG_0(n), true);
  }

  public Longs() {
    this(touchvgJNI.new_Longs__SWIG_1(), true);
  }

  public void setSize(int n) {
    touchvgJNI.Longs_setSize(swigCPtr, this, n);
  }

  public Longs(int v1, int v2) {
    this(touchvgJNI.new_Longs__SWIG_2(v1, v2), true);
  }

  public Longs(int v1, int v2, int v3, int v4) {
    this(touchvgJNI.new_Longs__SWIG_3(v1, v2, v3, v4), true);
  }

  public int count() {
    return touchvgJNI.Longs_count(swigCPtr, this);
  }

  public int get(int index) {
    return touchvgJNI.Longs_get(swigCPtr, this, index);
  }

  public void set(int index, int value) {
    touchvgJNI.Longs_set__SWIG_0(swigCPtr, this, index, value);
  }

  public void set(int index, int v1, int v2) {
    touchvgJNI.Longs_set__SWIG_1(swigCPtr, this, index, v1, v2);
  }

}
