/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package rhcad.touchvg.core;

public class MgJsonFile {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MgJsonFile(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MgJsonFile obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        touchvgJNI.delete_MgJsonFile(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MgJsonFile(String filename, boolean forRead) {
    this(touchvgJNI.new_MgJsonFile(filename, forRead), true);
  }

  public boolean opened() {
    return touchvgJNI.MgJsonFile_opened(swigCPtr, this);
  }

  public void close() {
    touchvgJNI.MgJsonFile_close(swigCPtr, this);
  }

}
