/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package touchvg.core;

public class MgCmdArcCSE extends MgCmdArc3P {
  private long swigCPtr;

  protected MgCmdArcCSE(long cPtr, boolean cMemoryOwn) {
    super(touchvgJNI.MgCmdArcCSE_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MgCmdArcCSE obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        touchvgJNI.delete_MgCmdArcCSE(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static String Name() {
    return touchvgJNI.MgCmdArcCSE_Name();
  }

  public static MgCommand Create() {
    long cPtr = touchvgJNI.MgCmdArcCSE_Create();
    return (cPtr == 0) ? null : new MgCommand(cPtr, false);
  }

  public String getName() {
    return touchvgJNI.MgCmdArcCSE_getName(swigCPtr, this);
  }

  public void release() {
    touchvgJNI.MgCmdArcCSE_release(swigCPtr, this);
  }

}
