/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package touchvg.core;

public class MgShapeIterator {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MgShapeIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MgShapeIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        touchvgJNI.delete_MgShapeIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MgShapeIterator(MgShapes shapes) {
    this(touchvgJNI.new_MgShapeIterator(MgShapes.getCPtr(shapes), shapes), true);
  }

  public MgShape getFirstShape() {
    long cPtr = touchvgJNI.MgShapeIterator_getFirstShape(swigCPtr, this);
    return (cPtr == 0) ? null : new MgShape(cPtr, false);
  }

  public MgShape getNextShape() {
    long cPtr = touchvgJNI.MgShapeIterator_getNextShape(swigCPtr, this);
    return (cPtr == 0) ? null : new MgShape(cPtr, false);
  }

  public void freeIterator() {
    touchvgJNI.MgShapeIterator_freeIterator(swigCPtr, this);
  }

}
